### PR TITLE
variance warning

### PR DESCRIPTION
**Pull request by nec4**
Development:
 - [ ] Implement feature / fix bug
 - [x] Add documentation
 - [ ] Add tests
 
 Checks:
 - [ ] Run `nosetests`
 - [ ] Check pep8 compliance

Hello. This PR adds a warning about CGnet model variance, which can be high among several different training runs. It offers a suggestion to use CGSchNet instead, which seems to be more stable. Let me know if there is anything else to change or improve.

### CODE REVIEW

**Review by Dom1L — APPROVED** [review]
lgtm

**Review by brookehus — APPROVED** [review]
looks good - feel free to also print a warning if you want (separate PR fine!)

**Comment by brookehus** [comment]
feel free to merge yourself

**Comment by nec4** [comment]
Thanks guys!

**Pull request merged**
